// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzbjt8HcqQm_BmujG2eIhtea0ShFX6lVc',
    appId: '1:834827156442:web:6ae527c2e7e594f4d49ee3',
    messagingSenderId: '834827156442',
    projectId: 'graduation-project-6e4d3',
    authDomain: 'graduation-project-6e4d3.firebaseapp.com',
    storageBucket: 'graduation-project-6e4d3.appspot.com',
    measurementId: 'G-ZG1FLF6EQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmD0KqWb_ydKfjAQ7sDAE7MU1AQGH6HM',
    appId: '1:834827156442:android:0d68967923326cb8d49ee3',
    messagingSenderId: '834827156442',
    projectId: 'graduation-project-6e4d3',
    storageBucket: 'graduation-project-6e4d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAspYaVf2r55YbkfnW1pugWbiWPaNjMk_w',
    appId: '1:834827156442:ios:40fc96f6e26b0594d49ee3',
    messagingSenderId: '834827156442',
    projectId: 'graduation-project-6e4d3',
    storageBucket: 'graduation-project-6e4d3.appspot.com',
    androidClientId: '834827156442-9ph41u7qstnpv6i14lebksfp5lm5milh.apps.googleusercontent.com',
    iosClientId: '834827156442-cpmrn5v5h08chn32d3ur336rbltfrsg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAspYaVf2r55YbkfnW1pugWbiWPaNjMk_w',
    appId: '1:834827156442:ios:40fc96f6e26b0594d49ee3',
    messagingSenderId: '834827156442',
    projectId: 'graduation-project-6e4d3',
    storageBucket: 'graduation-project-6e4d3.appspot.com',
    androidClientId: '834827156442-9ph41u7qstnpv6i14lebksfp5lm5milh.apps.googleusercontent.com',
    iosClientId: '834827156442-cpmrn5v5h08chn32d3ur336rbltfrsg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessCard',
  );
}
